### ISSUE TITLE
dont work with API

### ISSUE THREAD

**Issue by johnfelipe** [CharleeWa/ai-code-doctor#1]
![SNAG-0004](https://user-images.githubusercontent.com/428820/236955463-8f198c2c-3701-461b-a38e-c045b4ce6e66.png)

and i copy from here:

![SNAG-0005](https://user-images.githubusercontent.com/428820/236955597-410fe5d0-23c2-4e92-9461-ed67eacb76c2.png)

**Comment by cwandev** [comment]
Hi, @johnfelipe Does your OpenAI account support GPT-4? Mine does, so everything is working normally. You can try switching to GPT-3.5 and see if that works.
